In [4]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import joblib
import matplotlib.colors

plt.style.use("fivethirtyeight") 

In [109]:
class Perceptron:
    def __init__(self, eta:float=None, epochs:int=None):
        self.weights = np.random.randn(3) * 1e-4
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f"Initial weights before training: \n {self.weights}")
        self.eta = eta
        self.epochs = epochs
    
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
        
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}") 
        
        for epoch in range(self.epochs):
            print("--" * 10)
            print(f"For epoch >> {epoch}")
            print("--" * 10)
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"Error: \n{self.error}")
            
            self.weights = self.weights + (self.eta * np.dot(X_with_bias.T, self.error))
            print(f"Updated weights after epoch: {epoch}/{self.epochs}: \n {self.weights}")
            print("##" * 10)
    
    def predict(self, test_input):
        X_with_bias = np.c_[test_input, -np.ones((len(test_input), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return activation_function(z)
    
    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"Total loss: {total_loss} \n")
        return total_loss
    
    def _create_dir_return_path(self, model_dir, filename):
        os.makedirs(model_dir, exist_ok=True)
        return os.path.join(model_dir, filename)
    
    def save(self, filename, model_dir=None):
        if model_dir is not None:
            model_file_path = self._create_dir_return_path(model_dir, filename)
            joblib.dump(self, model_file_path)
        else:
            model_file_path = self._create_dir_return_path("model", filename)
            joblib.dump(self, model_file_path)
    
    def load(self, filepath):
        return joblib.load(filepath)



In [110]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    return X, y

In [114]:
AND = {
    "x1":[0, 0, 1, 1],
    "x2":[0, 1, 0, 1],
    "y" :[0, 1, 1, 1]
}

df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [115]:
X, y = prepare_data(df_AND)

In [116]:
ETA = 0.1
EPOCHS = 10

model_AND = Perceptron(eta=ETA, epochs=EPOCHS)
model_AND.fit(X, y)
_ = model_AND.total_loss()

Initial weights before training: 
 [ 8.91599516e-05 -1.70845855e-04 -3.97675769e-05]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
For epoch >> 0
--------------------
Predicted value after forward pass: 
[1 0 1 0]
Error: 
0   -1
1    1
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch: 0/10: 
 [ 0.10008916  0.19982915 -0.10003977]
####################
--------------------
For epoch >> 1
--------------------
Predicted value after forward pass: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
 [ 1.00089160e-01  1.99829154e-01 -3.97675769e-05]
####################
--------------------
For epoch >> 2
--------------------
Predicted value after forward pass: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
 [0.10008916 0.19982915 0.09996023]
####################
--------------------
For epoch >> 3
--------------------
